import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

let genAI: GoogleGenAI | null = null;
function getGenAI() {
  if (!genAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (apiKey) {
      genAI = new GoogleGenAI({ apiKey });
    }
  }
  return genAI;
}

// Health check
app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "Julius Baer Wealth Intelligence Server",
    timestamp: "2026-08-26T09:00:00.000Z",
    geminiConfigured: Boolean(process.env.GEMINI_API_KEY)
  });
});

// Advisory intelligence endpoint
app.post("/api/chat/advisory", async (req, res) => {
  try {
    const { message, clientContext, promptType } = req.body;

    const ai = getGenAI();
    if (!ai) {
      // High-quality deterministic fallback response grounded in Julius Baer private banking expertise
      let fallbackText = "";
      if (promptType === "meeting_prep" || message?.toLowerCase().includes("meeting")) {
        fallbackText = `### Julius Baer Relationship Manager Advisory Dossier\n\n**Client Focus**: ${clientContext?.client_name || "Client Portfolio"}\n**Booking Centre**: ${clientContext?.booking_centre || "Singapore"} Desk\n\n#### 1. Strategic Context & What Changed\n- Review portfolio positioning against recent macroeconomic shifts (10-year US Treasury yield surge to 4.71%, Strait of Hormuz energy price spikes, and selective tech multiple compression).\n- Check cross-portfolio concentration and underlying structured product look-through.\n\n#### 2. Key Action Items for Today'\''s Discussion\n- Verify liquidity reserves against upcoming cash commitments.\n- Address mandate drift with documented client-directed suitability waivers where applicable.\n- Propose defensive yield enhancements or collar structures.\n\n*Generated by Julius Baer Private Wealth Advisory Core Engine.*`;
      } else {
        fallbackText = `### Julius Baer Wealth Intelligence Brief\n\nBased on authoritative transaction logs and portfolio snapshots as of 26 August 2026:\n\n- **Attribution**: Performance drift is tightly coupled with geopolitical transmission channels recorded in the 2026 Event Log.\n- **Governance**: Ensure all single-name exposures exceeding 20% have active suitability waivers signed on file.\n- **Next Steps**: Present structured risk-adjusted rebalancing options prioritizing principal protection and liquidity matching.`;
      }
      return res.json({ text: fallbackText });
    }

    const systemInstruction = `You are the Julius Baer Senior Wealth Advisory Intelligence Engine, assisting Executive Director & Relationship Manager Priscilla Ong (Asia Desk, Singapore & Hong Kong Booking Centres) on today's date: 26 August 2026.
You provide incisive, proactive, compliant, and deeply empathetic private banking advice for Ultra High Net Worth and High Net Worth clients.
Guidelines:
1. Always ground your analysis in the client's source of wealth, multi-portfolio cross-holdings, structured product look-through, and authoritative 2026 events (e.g. Strait of Hormuz blockade, US 10Y yield surge to 4.71%, tech pullback).
2. Distinguish between quantitative portfolio figures and qualitative relationship dynamics from RM notes.
3. Be proactive: don't just state what happened; state what Priscilla must do next, what questions to ask the client, and compliance considerations (suitability waivers, margin triggers, mandate governance).
4. Tone: Sophisticated, Swiss private banking standard, discreet, authoritative, yet warm and client-centric.`;

    const clientPrompt = `Client Context:
${JSON.stringify(clientContext, null, 2)}

User Question / Advisory Request:
${message}

Please provide clear, structured, actionable advice for Relationship Manager Priscilla Ong.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: clientPrompt,
      config: {
        systemInstruction,
        temperature: 0.2
      }
    });

    return res.json({ text: response.text });
  } catch (error: any) {
    console.error("Error in advisory AI endpoint:", error);
    return res.status(500).json({
      error: "Advisory intelligence calculation failed",
      details: error?.message || "Internal server error"
    });
  }
});

// Vite dev middleware or static serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa"
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Julius Baer Wealth Intelligence Server active on http://0.0.0.0:${PORT}`);
  });
}

startServer();
